# Generated by Django 3.1 on 2020-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='用户自身ID')),
                ('sid', models.IntegerField(verbose_name='被滑的陌生人ID')),
                ('mark', models.CharField(choices=[('like', 'like'), ('superlike', 'superlike'), ('dislike', 'dislike')], max_length=16, verbose_name='滑动类型')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='滑动的时间')),
            ],
            options={
                'db_table': 'swiped',
            },
        ),
    ]
